[ASPA-12] Add home button
UoaWDCC/ASPA-EnrollmentForm pull request #102
Opened 2021-05-03 08:19 UTC by 3Bies

Issue:
Aspa form submitted page requires a home button to take the user back to the main page.

Solution:
By creating a home button and using an anchor to link to the main page.

Risk:
None

Reviewed By:
[Edit the message as to who reviewed it here]

2021-05-04 04:28 UTC, Ray-F requested changes
Overall, looks really good and behaves when I tested it on my local machine!

Just some really minor changes I suggested to improve the code readability/visibility. Sorry if they come across as too serious or strong toned, but it's just for clarity of what I mean.


Good work! 👍

2021-05-04 04:28 UTC, Ray-F commented on application/views/PaymentSuccessful.php
> +
Remove these spaces

2021-05-04 04:28 UTC, Ray-F commented on application/views/PaymentSuccessful.php
> +            -->
This comment is no longer needed now that `...href="/"...` has been updated

2021-05-04 04:28 UTC, Ray-F commented on application/views/PaymentSuccessful.php
> +            <br><a href="/"><img align="left" alt="Home Page Button" alt="Home Page" src="assets/images/iconmonstr-home-grey.svg" width="30px"></a><br><br>
1) Can you close the `<br />` statements and put these on separate lines for greater code visibility? Also, close the `img` tag too.

2) Let's also separate out the `<a>` tag and the `<img>` tag on separate lines and indented, like so...
```
<br />
<a ...>
    <img ... />
</a>
<br />
```

2021-05-05 07:15 UTC, mouyang2001 approved these changes
Looks good! Just implement those small changes as mentioned by Raymond.

2021-05-10 08:55 UTC, merged

2021-05-24 06:04 UTC, mouyang2001 reviewed
Looks good to me!