added the word *to* infront of event title on title page
UoaWDCC/ASPA-EnrollmentForm pull request #94
Opened 2021-04-24 09:45 UTC by mouyang2001

**Issue:**
"To" missing in front of the event title on the home page.

**Solution:**
Added "To" keyword in front of echo title. 

**Risk:**
May have reduced space available for the event title. 

**Reviewed By:**
Raymond Feng

2021-04-24 10:05 UTC, Ray-F commented
Commit titles should be "[ASPA-6] Add the word *to* in front of event title on title page"

Since this PR only has 1 commit, the PR title can be the same.

**The reason we include the story code is that Jira automates stuff based on the story code.**

Every commit (if it is related to a task) should have a [ASPA-##] in the commit, that way Jira will know when you've made a commit related to a story, and move the card on the development board to the next column automatically.

**We should use the word "Add" instead of "Added".** 

This is more of a semantic thing but that we chose to stick to when this project started. See this for more details around pros/cons: https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages

2021-04-24 10:06 UTC, Ray-F requested changes

2021-04-24 10:06 UTC, Ray-F commented on application/views/EnrollmentForm.php
>              <div class="div-placeholder"></div>
Change commit message/ PR title

2021-04-24 10:11 UTC, Ray-F requested changes

2021-04-24 10:11 UTC, Ray-F commented on application/views/EnrollmentForm.php
>              <div class="div-placeholder"></div>
See my last comment

2021-04-25 21:16 UTC, iyur874 approved these changes

2021-04-26 05:18 UTC, Ray-F approved these changes
LGTM! 👍

2021-04-26 06:26 UTC, merged