[ASPA-8] Add name display to confirmation email and change event photo
UoaWDCC/ASPA-EnrollmentForm pull request #95
Opened 2021-04-25 04:37 UTC by Metarock

**Issue:**
Currently when a confirmation email is sent to a recipient, "Hi there" is displayed, it should be "Hi {personName}". Additionally, background photo is not generic.  

**Solution:**
Added another argument into the function `sendConfirmationEmail` which takes in the recipient's name. 
`public function sendConfirmationEmail(string $recipientName, string $recipientEmail, string $paymentMethod, array $eventData)`

To change the background photo, change this line's URL to the desired background photo
` $EVENT_IMAGE = "https://user-images.githubusercontent.com/19633284/115980245-417e0500-a5df-11eb-9741-3b7a10499ef5.png";`

**Risk:**
There are currently no risk

**Reviewed By:**
[Edit the message as to who reviewed it here]

2021-04-25 05:33 UTC, jameszu reviewed
Looks good to me 😃
Just a note that in future sprints, we could get the name from the registration form in case of random input names. (We can discuss this later)

2021-04-25 07:19 UTC, Ray-F requested changes
On lines 279/280 (see screenshot), we need to update `"PERSON NAME"` to also be the correct name. This is because this name is used to identify the person as well in the email, especially important for some mailboxes as they use this to identify spam.

![image](https://user-images.githubusercontent.com/19633284/115984386-08538e00-a5fb-11eb-8bea-7d0a9f010601.png)

Also remember to update your DOD when every task is done! :) 

![image](https://user-images.githubusercontent.com/19633284/115984423-1dc8b800-a5fb-11eb-9e3a-951b69a8bc4e.png)

2021-04-26 05:17 UTC, Ray-F approved these changes
Awesome work, looks all good to me now! :)

2021-04-26 06:15 UTC, joewuthrich approved these changes

2021-04-26 06:28 UTC, merged